import {useCallback,useState} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {OrbitControls} from '@react-three/drei';
import {useExperienceStore} from '../../state/useExperienceStore';
import {EvidenceLabel} from '../ui/EvidenceLabel';
import type {OrganId} from '../../lib/types';
const content={
 pancreas:{title:'Pancreatic islet',text:'An islet contains several endocrine cell types. This simplified cluster uses amber for alpha cells and teal for beta cells; positions, counts and sizes are illustrative.',choices:['Beta cells','Alpha cells'],details:['Beta cells produce insulin. Incretin signalling is part of the regulation of secretion; this illustration does not calculate insulin release.','Alpha cells produce glucagon. Pancreatic regulation depends on glucose and multiple local and systemic signals; no exact secretion outcome is simulated.']},
 liver:{title:'Liver tissue',text:'Hepatocytes form an organized tissue that processes nutrients and responds to hormonal signals. The geometric arrangement here is a teaching diagram, not a histological reconstruction.',choices:['Hepatocytes','Tissue context'],details:['Hepatocytes perform many metabolic functions. This illustration locates cells in a conceptual tissue unit without predicting a retatrutide response.','Blood supply, hormonal signals and nutrient state all influence liver metabolism. The simplified arrangement is not to scale.']},
 gut:{title:'Intestinal epithelium',text:'A folded epithelial surface provides context for gut signalling. The folds, cell shapes and receptor placement are conceptual.',choices:['Epithelial cells','Gut–brain context'],details:['Epithelial cells line the digestive tract. This scene is anatomical context; not every depicted cell is asserted to express a target receptor.','Gut–brain communication involves neural and hormonal pathways. This simplified view does not predict appetite or gastric emptying.']},
 brain:{title:'Appetite and satiety network',text:'A simplified neural network introduces the idea of integrated signals. Its connections are not a literal map of appetite circuits.',choices:['Neuronal network','Systemic signals'],details:['Appetite regulation involves distributed neural circuits. These nodes and links are visual symbols, not reconstructed neurons.','Peripheral and central signals influence feeding behaviour. No individual behavioural response or clinical benefit is inferred.']},
} as const;
type Tissue=keyof typeof content;
function TissueScene({tissue,selected,onPick,onReady}:{tissue:Tissue;selected:number;onPick:(n:number)=>void;onReady:()=>void}){
 const [drawn,setDrawn]=useState(false);useFrame(()=>{if(!drawn){setDrawn(true);onReady();}});
 const nodes=Array.from({length:tissue==='brain'?15:35},(_,i)=>{
  if(tissue==='gut')return [((i%7)-3)*.36,(Math.floor(i/7)-2)*.34+.3*Math.cos((i%7)*1.1),.09*Math.sin(i)] as const;
  if(tissue==='liver')return [((i%7)-3)*.38+(Math.floor(i/7)%2)*.19,(Math.floor(i/7)-2)*.34,0] as const;
  const angle=i*2.399,r=.2+Math.sqrt(i)*.2;return [Math.cos(angle)*r,Math.sin(angle)*r,Math.sin(i*1.7)*.24] as const;
 });
 return <group rotation={[.1,.1,0]}>{nodes.map((p,i)=><group key={i} position={p}><mesh onClick={e=>{e.stopPropagation();onPick(i%3===0?1:0);}} scale={tissue==='gut'?[.16,.24,.14]:[.18,.18,.15]}><icosahedronGeometry args={[1,tissue==='liver'?0:3]}/><meshPhysicalMaterial color={tissue==='brain'?'#987ab8':i%3===0?'#c99664':'#609d9d'} emissive={(i%3===0?1:0)===selected?'#243b37':'#000'} roughness={.5}/></mesh><mesh scale={[.048,.05,.046]} position={[0,0,.12]}><sphereGeometry args={[1,12,8]}/><meshStandardMaterial color="#44566c" roughness={.65}/></mesh></group>)}{tissue==='brain'&&nodes.slice(1).map((p,i)=>{const prev=nodes[i];const points=new Float32Array([...prev,...p]);return <line key={i}><bufferGeometry><bufferAttribute attach="attributes-position" args={[points,3]}/></bufferGeometry><lineBasicMaterial color="#685681" transparent opacity={.7}/></line>;})}</group>;
}
export function CellExperience(){
 const s=useExperienceStore();const initial:Tissue=s.selectedOrganId==='liver'?'liver':s.selectedOrganId==='stomach'||s.selectedOrganId==='smallIntestine'?'gut':s.selectedOrganId==='brain'?'brain':'pancreas';
 const [tissue,setTissue]=useState<Tissue>(initial),[selected,setSelected]=useState(0),[ready,setReady]=useState(false);const onReady=useCallback(()=>setReady(true),[]);const info=content[tissue];
 return <main className="molecular-stage"><header className="molecular-header"><div><div className="panel-kicker">EXPLICIT SCALE CHANGE · NOT TO SCALE</div><h1>From organ to tissue</h1><p>This is a separate educational illustration, not a physically continuous zoom into the anatomical model.</p></div><EvidenceLabel label="Conceptual educational animation"/></header>
 <div className="tissue-tabs">{(Object.keys(content) as Tissue[]).map(id=><button aria-pressed={tissue===id} key={id} className={tissue===id?'active':''} onClick={()=>{setTissue(id);setSelected(0);}}>{id==='gut'?'Gut':id[0].toUpperCase()+id.slice(1)}</button>)}</div>
 <div className="molecular-layout"><section className="molecular-visual-card"><div className="cell-canvas" data-ready={ready}><Canvas camera={{position:[0,0,4.6],fov:40}} dpr={[1,1.5]}><color attach="background" args={['#09151e']}/><ambientLight intensity={1}/><directionalLight position={[-2,4,4]} intensity={2.5}/><TissueScene tissue={tissue} selected={selected} onPick={setSelected} onReady={onReady}/><OrbitControls enableDamping minDistance={2.5} maxDistance={8}/></Canvas></div><div className="molecule-scale-badge">Cell-level illustration · click a cell or use the buttons</div></section><aside className="molecular-info"><h2>{info.title}</h2><p>{info.text}</p><div className="cell-choices">{info.choices.map((name,i)=><button key={name} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{name}</button>)}</div><p aria-live="polite">{info.details[selected]}</p><button className="body-link" onClick={()=>s.setStage('receptors')}>Enter cell-membrane view →</button><button className="secondary-action" onClick={()=>s.setStage('peptide')}>Open experimental molecular structure</button><button className="secondary-action" onClick={()=>{s.selectOrgan(({pancreas:'pancreas',liver:'liver',gut:'stomach',brain:null}[tissue]) as OrganId|null);s.setStage('body');}}>Back to anatomy and timeline</button></aside></div></main>;
}
