import {useCallback,useEffect,useState} from 'react';
import {ChevronRight,Info,Pause,Play,RotateCcw} from 'lucide-react';
import type {ReceptorId} from '../../lib/types';
import {molecularStructures} from '../../data/molecularStructures';
import {useExperienceStore} from '../../state/useExperienceStore';
import {EvidenceLabel} from '../ui/EvidenceLabel';
import {ConceptualScene} from './ConceptualScene';
import {ExperimentalBindingViewer} from './ExperimentalBindingViewer';
const receptorCopy:Record<ReceptorId,{name:string;detail:string}>={
 GLP1R:{name:'GLP-1 receptor',detail:'GLP-1R is a class B G-protein-coupled receptor. The deposited 8YWF model captures retatrutide bound to the receptor; it does not show motion, affinity or downstream signaling.'},
 GIPR:{name:'GIP receptor',detail:'GIPR is an incretin receptor. The deposited 8YW4 model captures a receptor-bound peptide conformation; it does not imply the same affinity, potency or downstream response as GLP-1R.'},
 GCGR:{name:'Glucagon receptor',detail:'GCGR participates in glucagon signalling and metabolic regulation. The deposited 6LMK model captures glucagon bound to GCGR with an attached G protein; it does not establish retatrutide-specific binding or signaling.'},
};
export function MolecularExperience(){
 const s=useExperienceStore(),receptor=s.selectedReceptorId??'GLP1R';
 const [progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[reset,setReset]=useState(0),[ready,setReady]=useState(false),[bindingReady,setBindingReady]=useState(false);
 const [bindingSettings,setBindingSettings]=useState({peptide:true,receptor:true,labels:false,interface:true,representation:'cartoon' as const,peptideRepresentation:'ball-and-stick' as const,receptorRepresentation:'cartoon' as const});
 const onReady=useCallback(()=>setReady(true),[]),onBindingReady=useCallback(()=>setBindingReady(true),[]);
 useEffect(()=>{if(!playing||s.reducedMotion)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now(),delta=(now-last)/9000;last=now;setProgress(p=>Math.min(1,p+delta));},60);return ()=>clearInterval(timer);},[playing,s.reducedMotion]);
 useEffect(()=>{if(progress>=1)setPlaying(false);},[progress]);
 useEffect(()=>{if(s.reducedMotion)setPlaying(false);},[s.reducedMotion]);
 const info=receptorCopy[receptor],structure=molecularStructures.find(x=>x.receptor===receptor)??null,bound=progress>=.5,actual=structure!==null;
 const change=(id:ReceptorId)=>{s.selectReceptor(id);setProgress(0);setPlaying(false);setReady(false);setBindingReady(false);};
 return <main className="molecular-stage"><header className="molecular-header"><div><div className="panel-kicker">RECEPTOR ENGAGEMENT · STRUCTURE-ANCHORED</div><h1>{actual?'Receptor binding in experimental coordinates':'Three receptor contexts'}</h1><p>{actual?`Explore the deposited ${structure.pdbId} receptor-bound complex, then use the sequence controls to connect the observed structure to the binding concept. Coordinates show one captured conformation, not molecular motion.`:'Explore a simplified sequence from a peptide approaching a receptor to intracellular signalling. No deposited glucagon-receptor complex is configured here, so this scene remains explicitly conceptual.'}</p></div><EvidenceLabel label={actual?'Experimental structure':'Conceptual educational animation'}/></header>
 <div className="receptor-tabs" role="tablist" aria-label="Receptor targets">{(['GLP1R','GIPR','GCGR'] as ReceptorId[]).map(id=><button key={id} role="tab" aria-selected={receptor===id} tabIndex={receptor===id?0:-1} onKeyDown={e=>{const ids:ReceptorId[]=['GLP1R','GIPR','GCGR'];if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const n=(ids.indexOf(id)+(e.key==='ArrowRight'?1:2))%3;change(ids[n]);(e.currentTarget.parentElement?.children[n] as HTMLElement)?.focus();}}} className={receptor===id?'active':''} onClick={()=>change(id)}>{id}<small>{receptorCopy[id].name}</small></button>)}</div>
 <div className="molecular-layout"><section className={`molecular-visual-card ${actual?'experimental-binding-card':''}`}><div className="binding-view-toolbar">{actual?<span><b>OBSERVED COMPLEX</b> · PDB {structure.pdbId}</span>:<span><b>CONCEPTUAL SEQUENCE</b> · NO EXPERIMENTAL COMPLEX CONFIGURED</span>}{actual&&<div className="binding-view-controls"><label><input type="checkbox" checked={bindingSettings.peptide} onChange={e=>setBindingSettings({...bindingSettings,peptide:e.target.checked})}/>{structure.peptideName}</label><label><input type="checkbox" checked={bindingSettings.receptor} onChange={e=>setBindingSettings({...bindingSettings,receptor:e.target.checked})}/>{structure.receptor}</label><label><input type="checkbox" checked={bindingSettings.interface} onChange={e=>setBindingSettings({...bindingSettings,interface:e.target.checked})}/>Observed proximity</label><select aria-label="Experimental representation" value={bindingSettings.representation} onChange={e=>setBindingSettings({...bindingSettings,representation:e.target.value as typeof bindingSettings.representation})}><option value="cartoon">Ribbon + atoms</option><option value="ball-and-stick">Ball and stick</option><option value="spacefill">Space filling</option><option value="molecular-surface">Molecular surface</option></select></div>}</div><div className="molecular-canvas" data-ready={actual?bindingReady:ready} data-progress={progress.toFixed(3)}>{actual?<ExperimentalBindingViewer key={structure.id} config={structure} settings={bindingSettings} reset={reset} onReady={onBindingReady}/>:<ConceptualScene progress={progress} reset={reset} onReady={onReady}/>}</div><div className="molecular-legend">{actual?<><span><i className="molecular-dot peptide"/>Observed {structure.peptideName}</span><span><i className="molecular-dot receptor"/>{structure.receptor} backbone</span><span><i className="molecular-dot contact"/>Atoms within 4 Å</span></>:<><span><i className="molecular-dot peptide"/>Peptide symbol</span><span><i className="molecular-dot receptor"/>Receptor</span><span><i className="molecular-dot signal"/>Signal</span></>}</div>{actual?<div className="molecule-scale-badge">Atomic coordinates · one deposited conformation · not a dynamic simulation</div>:<><div className="concept-scene-labels"><span>Extracellular space</span><span>Membrane cutaway</span><span>Intracellular space</span></div><div className="molecule-scale-badge">Conceptual geometry · no experimental coordinates in this animation</div></>}</section>
 <aside className="molecular-info"><h2>{info.name}</h2><p>{info.detail}</p>{['Peptide approaches','Binding / activation concept','Intracellular signalling concept'].map((name,i)=><div className={`molecular-step ${progress>=[0,.48,.6][i]?'active':''}`} key={name}><span className="step-number">0{i+1}</span><strong>{name}</strong></div>)}
 <label className="slider-label" htmlFor="binding-progress">Explore the sequence</label><input id="binding-progress" type="range" min={0} max={1} step={.01} value={progress} onChange={e=>{setPlaying(false);setProgress(+e.target.value);}}/>
 <div className="molecular-actions"><button className="primary-action" onClick={()=>{if(s.reducedMotion){setProgress(p=>Math.min(1,p+.25));}else{if(progress>=1)setProgress(0);setPlaying(!playing);}}}>{playing?<Pause size={15}/>:<Play size={15}/>} {s.reducedMotion?'Next animation step':playing?'Pause animation':'Play animation'}</button><button className="secondary-action" aria-label="Reset receptor view" onClick={()=>{setPlaying(false);setProgress(0);setReset(v=>v+1);}}><RotateCcw size={15}/>Reset</button></div>
 <button className="binding-toggle" aria-pressed={bound} onClick={()=>{setProgress(bound?0:.75);setPlaying(false);}}>{bound?'Binding concept on':'Show binding concept'}</button>
 {structure&&<div className="structure-reference"><p>Observed coordinates are available in the same local entry:</p><a href={`https://www.rcsb.org/structure/${structure.pdbId}`} target="_blank" rel="noreferrer">PDB {structure.pdbId} ↗</a><p className="binding-readout"><strong>Observed proximity</strong><span>Amber atoms mark receptor atoms within 4 Å of the deposited peptide. This is a geometric cue, not an affinity estimate.</span></p><button className="body-link" onClick={()=>s.setStage('peptide')}>Open full Mol* structure viewer</button></div>}
 <div className="molecular-caveat"><Info size={15}/><span>No exact binding residues, affinity or clinical outcomes are inferred from this animation. Green pulses are an explanatory symbol, not simulated biochemical quantities.</span></div><button className="body-link" onClick={()=>s.setStage('body')}><ChevronRight size={15}/>Continue to whole-body anatomy</button></aside></div></main>;
}
