export function SourcesAndNotes(){return <main className="placeholder-stage sources-page">
 <div className="panel-kicker">SOURCES & LIMITATIONS</div><h1>Reference anatomy.<br/>Illustrative physiology.</h1>
 <p>The viewer combines licensed anatomical meshes with educational materials, layer controls and a simplified concentration timeline.</p>
 <h2>Anatomy</h2><p><a href="https://github.com/ashemag/human-atlas">Human Atlas by ashemag</a> supplies the prepared geometry. HRA female v1.5 provides the skin and organ surfaces. BodyParts3D provides torso muscles, ribs and stomach. The datasets have been registered into a composite educational reference, with source IDs preserved. Registration, colors and surface detail are illustrative.</p>
 <p>Human Reference Atlas / HuBMAP: Kristen Browne and Heidi Schlehlein, <a href="https://doi.org/10.48539/HBM352.BTSQ.586">3D Reference Organ Set for Female v1.5</a> (2023). <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.</p>
 <p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International. <a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html">Dataset licence</a>.</p>
 <p>The head and brain atlas is adapted from <a href="https://github.com/bubblik525/head">Human Head Atlas</a>, which selects geometry from <a href="https://github.com/LluisV/Z-Anatomy/tree/PC-Version">Z-Anatomy / BodyParts3D</a>. The 708 head structures are redistributed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>; source metadata and full notices are retained in the bundled head attribution file.</p>
 <h2>Peptide and timeline</h2><p>Retatrutide is represented as an investigational GLP-1, GIP and glucagon receptor agonist. The story gives system context without predicting treatment outcomes. <a href="https://doi.org/10.1056/NEJMoa2301972">Jastreboff et al., phase 2 trial (2023)</a>.</p>
 <p>The half-life model uses a user-adjustable illustrative value, a 0.75-day invented linear rise, and exponential elimination. One unit is the single-input peak reference. Repeated inputs are added without rescaling or capping. It does not reproduce a study's concentration data. Particle intensity is a saturating visual encoding of relative concentration, not measured organ exposure, receptor occupancy, efficacy, or a clinical outcome. The weekly pattern is only an arithmetic example. Real pharmacokinetics vary.</p>
 <h2>Molecular references</h2><p><a href="https://www.rcsb.org/structure/8YWF">PDB 8YWF</a> and <a href="https://www.rcsb.org/structure/8YW4">PDB 8YW4</a> contain observed retatrutide complexes with GLP-1R and GIPR; their verified label chains are E (ligand) / F (receptor) in 8YWF, and F (ligand) / E (receptor) in 8YW4, with 33 and 27 ligand residues represented. <a href="https://www.rcsb.org/structure/6LMK">PDB 6LMK</a> contains a glucagon-bound GCGR complex with Gs and a stabilizing nanobody; its verified label chains are F (glucagon) / E (GCGR), with 29 glucagon residues represented. Missing residues are not reconstructed. These structures are single captured conformations, not molecular-dynamics trajectories, affinity measurements or evidence of retatrutide-specific GCGR binding.</p>
 <h2>Software and adaptations</h2><p>React, TypeScript, Vite, Three.js, Mol*, Zustand, Recharts and Lucide power this prototype. Prepared geometry, materials, cropping and interactions are adapted locally. <a href={`${import.meta.env.BASE_URL}ATTRIBUTION.md`}>Full attribution and modification notes</a>.</p>
 </main>}
