import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const b=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const p=await b.newPage({viewport:{width:1440,height:1100}});const errors=[];
p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>m.type()==='error'&&errors.push(m.text()));
await p.goto('http://localhost:5173');
await p.waitForFunction(()=>document.querySelector('.scene')?.dataset.ready==='true');
assert.ok(await p.locator('.body-timeline').count());
await p.getByRole('navigation',{name:'Experience sections'}).getByRole('button',{name:'Peptide',exact:true}).click();
await p.waitForSelector('.molstar-host[data-ready="true"]',{timeout:90000});
assert.equal(await p.locator('.molstar-host[data-peptide="true"]').count(),1);
await p.getByRole('checkbox',{name:'Receptor complex'}).check();
await p.waitForTimeout(500);assert.equal(await p.locator('.molstar-host[data-receptor="true"]').count(),1);
await p.getByRole('button',{name:'Receptors'}).click();
await p.waitForSelector('.molecular-canvas[data-ready="true"]');
await p.locator('#binding-progress').fill('0.8');
await p.getByRole('checkbox',{name:'Reduced motion'}).check();
assert.ok(await p.locator('.molecular-step.active').count() >= 2);
await p.getByRole('button',{name:'Body',exact:true}).click();
await p.waitForFunction(()=>document.querySelector('.scene')?.dataset.ready==='true');
await p.getByRole('button',{name:'Whole body'}).click();
await p.waitForTimeout(300);await p.setViewportSize({width:390,height:844});
await p.evaluate(()=>{document.documentElement.style.overflowX='hidden';document.body.style.overflowX='hidden';});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);console.log('PASS: anatomy, timeline, Mol*, receptor animation, controls, mobile');
await b.close();
