import {ArrowLeft,ChevronLeft,ChevronRight,Crosshair,Pause,Play,X} from 'lucide-react';
import {organContent} from '../../data/organs';
import {pathwaySteps} from '../../data/pathwaySteps';
import {useExperienceStore} from '../../state/useExperienceStore';
import {EvidenceLabel} from '../ui/EvidenceLabel';
export function OrganInfoPanel(){
 const s=useExperienceStore(),organ=s.selectedOrganId?organContent[s.selectedOrganId]:null,step=pathwaySteps[s.pathwayStep];
 const go=(index:number)=>{const n=Math.min(7,Math.max(0,index));const organId=pathwaySteps[n].organId;s.setPathwayStep(n);s.selectOrgan(organId);s.setLayerMode('normal');if(organId&&organId!=='muscle')s.requestOrganCamera(organId);else s.requestBodyCamera();if(organId==='muscle')s.setLayerVisibility('muscles',true);};
 return <aside className="organ-panel">
  <div className="story-card"><div className="panel-kicker">FOLLOW THE PEPTIDE · {s.pathwayStep+1} / 8</div><h2>{step.title}</h2><p>{step.text}</p>
   <div className="story-controls"><button aria-label="Previous pathway step" disabled={s.pathwayStep===0} onClick={()=>go(s.pathwayStep-1)}><ChevronLeft size={17}/></button><button onClick={()=>{if(s.pathwayStep===7)go(0);s.setVideoMode(true);s.setPathwayPlaying(!s.pathwayPlaying);}}>{s.pathwayPlaying?<Pause size={15}/>:<Play size={15}/>} {s.pathwayPlaying?'Pause story':'Play visual story'}</button><button aria-label="Next pathway step" disabled={s.pathwayStep===7} onClick={()=>go(s.pathwayStep+1)}><ChevronRight size={17}/></button></div><small>Story steps are not timed physiological events.</small>
  </div>
  {s.headSelection?<section className="selected-organ" aria-live="polite"><div className="panel-topline"><span className="panel-kicker">HEAD ATLAS · {s.headSelection.system.toUpperCase()}</span><button className="close-button" aria-label="Close head structure details" onClick={()=>{s.selectHeadPart(null);s.selectOrgan(null);}}><X size={16}/></button></div><h2>{s.headSelection.name}</h2><p>{s.headSelection.side} side · source mesh from the vendored Z-Anatomy / BodyParts3D head atlas.</p><EvidenceLabel label="Structural proxy"/><p>The atlas preserves the published source geometry and hierarchy. Position, scale and colour are adapted for this educational whole-body reference.</p><button className="secondary-action" onClick={()=>{s.selectHeadPart(null);s.selectOrgan(null);s.requestBodyCamera();}}><ArrowLeft size={15}/>Back to whole-body anatomy</button></section>:organ?<section className="selected-organ" aria-live="polite"><div className="panel-topline"><span className="panel-kicker">ANATOMICAL CONTEXT</span><button className="close-button" aria-label="Close organ information" onClick={()=>s.selectOrgan(null)}><X size={16}/></button></div><h2>{organ.displayName}</h2><p>{organ.shortDescription}</p><EvidenceLabel label="Conceptual educational animation"/><p>{organ.detailedDescription}</p><p className="caveat">{organ.caveat}</p><button className="primary-action" onClick={()=>s.requestOrganCamera(organ.id)}><Crosshair size={15}/>Isolate organ</button><button className="body-link" onClick={()=>{s.setPathwayPlaying(false);s.setStage(organ.cellularSceneId?'cell':'receptors');}}>{organ.cellularSceneId?'Explore tissue / cell view':'Explore receptor concept'}</button><button className="secondary-action" onClick={()=>{s.selectOrgan(null);s.requestBodyCamera();}}><ArrowLeft size={15}/>Back to anatomy</button></section>:<section className="selected-organ"><h2>Select an organ</h2><p>Click the model or use the organ list to inspect its anatomy and educational context. You can isolate structures hidden behind the liver or lungs.</p></section>}
  <details className="reference-note"><summary>Sources & anatomical limits</summary><p>HRA female body and organs, combined with registered BodyParts3D male torso muscles, ribs and stomach. This is a composite illustration, not one person's scan or a validated anatomical registration.</p><p>Surface colors and texture are illustrative. No organ drug concentrations or guaranteed effects are represented.</p><a href={`${import.meta.env.BASE_URL}ATTRIBUTION.md`} target="_blank" rel="noreferrer">Credits and licences ↗</a></details>
 </aside>;
}
